apiVersion: v1
kind: Alert
app: postgreSQL
version: 1.0.0
appVersion:
- "12"
configurations:
- kind: Prometheus
  data: |
    - alert: InstanceDown
      expr: pg_up == 0
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Instance down {{$labels.instance}}
    - alert: LowUpTime
      expr: time() - pg_postmaster_start_time_seconds < 3600
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Low uptime of postmaster in instance {{$labels.instance}}
    - alert: MaxWriteBufferReached
      expr: rate(pg_stat_bgwriter_maxwritten_clean[5m]) > 0
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Background writer stops for max. write buffers reached in instance {{$labels.instance}}
    - alert: HighWALFilesArchiveErrorRate
      expr: |
        rate(pg_stat_archiver_failed_count[5m]) /
        (rate(pg_stat_archiver_archived_count[5m]) +
          rate(pg_stat_archiver_failed_count[5m])) > 0.1
      for: 10m
      labels:
        severity: page
      annotations:
        summary: High error rate in WAL files archiver in instance {{$labels.instance}}
    - alert: LowAvailableConnections
      expr: |
        sum(pg_stat_activity_count) by (instance)  /
        ((sum(pg_settings_max_connections) by (instance)) -
          sum(pg_settings_superuser_reserved_connections) by (instance)) > 0.85
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Low available connections in instance {{$labels.instance}}
    - alert: HighResponseTime
      expr: |
        avg(rate(pg_stat_activity_max_tx_duration{datname!~"template.*"}[5m])) by (datname) > 2 * 60
      for: 10m
      labels:
        severity: page
      annotations:
        summary: High response time in database {{$labels.datname}}
    - alert: LowCacheHitRate
      expr: |
        avg(rate(pg_stat_database_blks_hit{datname!~"template.*"}[5m]) /
        (rate(pg_stat_database_blks_hit{datname!~"template.*"}[5m]) +
          rate(pg_stat_database_blks_read{datname!~"template.*"}[5m]))) < 0.9
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Low cache hit rate in database {{$labels.datname}}
    - alert: DeadLocksInDatabase
      expr: |
        rate(pg_stat_database_deadlocks{datname!~"template.*"}[5m]) > 0
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Deadlocks in database {{$labels.datname}}
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "pg_up == 0",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "InstanceDown",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "time() - pg_postmaster_start_time_seconds < 3600",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "LowUpTime",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "rate(pg_stat_bgwriter_maxwritten_clean[5m]) > 0",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "MaxWriteBufferReached",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "rate(pg_stat_archiver_failed_count[5m]) / \n(rate(pg_stat_archiver_archived_count[5m]) + \n  rate(pg_stat_archiver_failed_count[5m])) > 0.1\n",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "HighWALFilesArchiveErrorRate",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "sum(pg_stat_activity_count) by (instance)  / \n((sum(pg_settings_max_connections) by (instance)) - \n  sum(pg_settings_superuser_reserved_connections) by (instance)) > 0.85\n",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "LowAvailableConnections",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "avg(rate(pg_stat_activity_max_tx_duration{datname!~\"template.*\"}[5m])) by (datname) > 2 * 60\n",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "HighResponseTime",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "avg(rate(pg_stat_database_blks_hit{datname!~\"template.*\"}[5m]) / \n(rate(pg_stat_database_blks_hit{datname!~\"template.*\"}[5m]) + \n  rate(pg_stat_database_blks_read{datname!~\"template.*\"}[5m]))) < 0.9\n",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "LowCacheHitRate",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "rate(pg_stat_database_deadlocks{datname!~\"template.*\"}[5m]) > 0\n",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "DeadLocksInDatabase",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
descriptionFile: ALERTS.md
