apiVersion: v1
kind: SetupGuide
app: Istio
version: 1.0.0
appVersion:
- '1.5'
configurations:
- name: patch.yaml
  file: include/patch.yaml
- name: rules.yaml
  file: include/istio-recording-rules.yaml
- name: sysdig-agent.yaml
  file: include/sysdig-agent.yaml
descriptionFile: INSTALL.md
